import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const codecPro = localFont({
  src: [
    { path: "../../fonts/CodecPro-Thin.ttf", weight: "100", style: "normal" },
    { path: "../../fonts/CodecPro-ThinItalic.ttf", weight: "100", style: "italic" },
    { path: "../../fonts/CodecPro-ExtraLight.ttf", weight: "200", style: "normal" },
    { path: "../../fonts/CodecPro-ExtraLightItalic.ttf", weight: "200", style: "italic" },
    { path: "../../fonts/CodecPro-Light.ttf", weight: "300", style: "normal" },
    { path: "../../fonts/CodecPro-LightItalic.ttf", weight: "300", style: "italic" },
    { path: "../../fonts/CodecPro-Regular.ttf", weight: "400", style: "normal" },
    { path: "../../fonts/CodecPro-Italic.ttf", weight: "400", style: "italic" },
    { path: "../../fonts/CodecPro-News.ttf", weight: "500", style: "normal" },
    { path: "../../fonts/CodecPro-NewsItalic.ttf", weight: "500", style: "italic" },
    { path: "../../fonts/CodecPro-Bold.ttf", weight: "700", style: "normal" },
    { path: "../../fonts/CodecPro-BoldItalic.ttf", weight: "700", style: "italic" },
    { path: "../../fonts/CodecPro-ExtraBold.ttf", weight: "800", style: "normal" },
    { path: "../../fonts/CodecPro-ExtraBoldItalic.ttf", weight: "800", style: "italic" },
    { path: "../../fonts/CodecPro-Heavy.ttf", weight: "900", style: "normal" },
    { path: "../../fonts/CodecPro-HeavyItalic.ttf", weight: "900", style: "italic" },
    { path: "../../fonts/CodecPro-Fat.ttf", weight: "900", style: "normal" },
    { path: "../../fonts/CodecPro-FatItalic.ttf", weight: "900", style: "italic" },
    { path: "../../fonts/CodecPro-Ultra.ttf", weight: "900", style: "normal" },
    { path: "../../fonts/CodecPro-UltraItalic.ttf", weight: "900", style: "italic" },
    { path: "../../fonts/CodecPro-UltraBlack.ttf", weight: "950", style: "normal" },
    { path: "../../fonts/CodecPro-UltraBlackItalic.ttf", weight: "950", style: "italic" },
  ],
  variable: "--font-codec-pro",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${codecPro.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
